language: fortran

sudo: required

addons:
  apt:
    packages:
      - mpich
      - libmpich-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev

env:
  - SOLVER=maxwell
  - SOLVER=drift
  - SOLVER=acoustic
  - SOLVER=poisson
  - STYLE=1

script:
  - bash bin/travis.sh
